# FAKE REVIEW NODE EMBEDDING

In [1]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting stellargraph
  Downloading stellargraph-1.2.1-py3-none-any.whl (435 kB)
     |████████████████████████████████| 435 kB 5.1 MB/s
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.3.5)
Requirement already satisfied: gensim>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (3.6.0)
Requirement already satisfied: tensorflow>=2.1.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (2.9.2)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (2.8.8)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.21.6)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (3.2.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.7.3)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.0.2)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from gensim>=3.4.0->stellargraph) (6.3.0)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.8/dist-packages (from gensim>=3.4.0->stellargraph) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24->stellargraph) (2022.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->stellargraph) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->stellargraph) (1.2.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.14.1)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.4.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (14.0.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (21.3)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.1.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.28.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (57.4.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.51.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.3.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (4.4.0)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.12)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.19.6)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.2.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.6.3)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.1.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.8/dist-packages (from astunparse>=1.6.0->tensorflow>=2.1.0->stellargraph) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.15.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.6.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.23.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.4.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (5.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2022.12.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.2.2)
Installing collected packages: stellargraph
Successfully installed stellargraph-1.2.1

In [2]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [3]:
#importing libraries
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import statistics
import math
import os
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.metrics import confusion_matrix
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

import re
pd.set_option('max_colwidth', 800)


#importing Libraies
import networkx as nx
import matplotlib.pyplot as plt
from numpy import genfromtxt
import collections
from collections import OrderedDict

import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression,LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [4]:
#loading dataset
df=pd.read_csv('/content/deceptive.csv')
df.head()

,deceptive,hotel,polarity,source,text,Class
0,truthful,conrad,positive,TripAdvisor,"We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n",1
1,truthful,hyatt,positive,TripAdvisor,"Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n",1
2,truthful,hyatt,positive,TripAdvisor,"This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...",1
3,truthful,omni,positive,TripAdvisor,"The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n",1
4,truthful,hyatt,positive,TripAdvisor,"I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Michigan Avenue shopping district. \n",1

In [5]:
d = []
for i in range(1600):
    s = i+1
    d.append(s)

In [6]:
#d

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

In [7]:
df.insert(0, 'Index', d)
df.head()

,Index,deceptive,hotel,polarity,source,text,Class
0,1,truthful,conrad,positive,TripAdvisor,"We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n",1
1,2,truthful,hyatt,positive,TripAdvisor,"Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n",1
2,3,truthful,hyatt,positive,TripAdvisor,"This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...",1
3,4,truthful,omni,positive,TripAdvisor,"The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n",1
4,5,truthful,hyatt,positive,TripAdvisor,"I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Michigan Avenue shopping district. \n",1

In [8]:
df.shape

(1600, 7)

In [9]:
df['Class'].value_counts()

1    800
0    800
Name: Class, dtype: int64

In [10]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,Index,deceptive,hotel,polarity,source,text,Class
0,701,deceptive,sofitel,positive,MTurk,"My wife and I recently stayed at this hotel for a fun anniversary weekend away from the kids. Upon check in we were pleasantly surprised by the decor, the location to so many downtown attractions and the attentiveness of the staff. As a seasoned traveler for business I consider myself somewhat savvy when it comes to service and accommodations. This hotel certainly delivers on both accounts. My wife and I had not intended on eating in the hotel restaurant, but after reviewing the menu we thought we would give it a try. WOW! Service was outstanding and the food was amazing. We truly enjoyed our dining experience. All in all I would not hesitate to recommend this hotel to anyone I meet. \n",0
1,1171,truthful,intercontinental,negative,Web,"When you check into a hotel after being stuck in a airport, you areusually not in the best of mood. I, working in a upscale hotel, do encounter many guests checking in who this has happened to. All they want is a friendly face and a smooth check in. The desk clerk who checked me in at this property, did neither. She was short, rude, handed me my keys and walked away. I would never go back to this property due to this.\n",1
2,869,truthful,fairmont,negative,Web,"Maybe it was because we booked thru priceline that we were treated like second rate guest - couldn't get a room thru Fairmont website as busy weekend with Ryder Cup.....but never have had this experience in using priceline before. The night time check in girl was rude and unhelpful. We were told no options to pay for upgrade or king bed and that we were stuck with two tiny beds and a ugly room. We had comforter with dirt in several places - and a bathroom for handicap with no counter space - had to use ironing board for toiletries. This hotel is huge and not at capacity - may have had a renovation but the good look of this hotel stops at the lobby. Hallways, rooms, carpet run down - just not what you come to expect of a fairmont. I have stayed in many all over the world and this is by ...",1
3,1212,deceptive,fairmont,negative,MTurk,"We booked an American Girl Place package at Fairmont Chicago Millennium Park. Told that we'd have a room with a nice view, apparently their idea of a nice view is of another building! Ended up getting a smoking room when we booked non-smoking, cost us $100 more a night than we were told, and staff was incredibly rude at the restaurant. Would never recommend coming here for any reason whatsoever!\n",0
4,637,deceptive,ambassador,positive,MTurk,"The Ambassador East Hotel is a business that certainly strives to keep its customers satisfied. Upon my entrance at the Ambassador East, I was greeted warmly. The staff was incredibly pleasant, and the accommodations were top-knotch. The food served at the award-winning 'Pump Room' was to die for, and the service was fast but friendly. \n",0

### Data preprocessing

In [11]:
# dropping unnecessary columns. 
df.drop(['deceptive', 'hotel', 'polarity', 'source'], axis = 1, inplace=True)
df.head()

,Index,text,Class
0,701,"My wife and I recently stayed at this hotel for a fun anniversary weekend away from the kids. Upon check in we were pleasantly surprised by the decor, the location to so many downtown attractions and the attentiveness of the staff. As a seasoned traveler for business I consider myself somewhat savvy when it comes to service and accommodations. This hotel certainly delivers on both accounts. My wife and I had not intended on eating in the hotel restaurant, but after reviewing the menu we thought we would give it a try. WOW! Service was outstanding and the food was amazing. We truly enjoyed our dining experience. All in all I would not hesitate to recommend this hotel to anyone I meet. \n",0
1,1171,"When you check into a hotel after being stuck in a airport, you areusually not in the best of mood. I, working in a upscale hotel, do encounter many guests checking in who this has happened to. All they want is a friendly face and a smooth check in. The desk clerk who checked me in at this property, did neither. She was short, rude, handed me my keys and walked away. I would never go back to this property due to this.\n",1
2,869,"Maybe it was because we booked thru priceline that we were treated like second rate guest - couldn't get a room thru Fairmont website as busy weekend with Ryder Cup.....but never have had this experience in using priceline before. The night time check in girl was rude and unhelpful. We were told no options to pay for upgrade or king bed and that we were stuck with two tiny beds and a ugly room. We had comforter with dirt in several places - and a bathroom for handicap with no counter space - had to use ironing board for toiletries. This hotel is huge and not at capacity - may have had a renovation but the good look of this hotel stops at the lobby. Hallways, rooms, carpet run down - just not what you come to expect of a fairmont. I have stayed in many all over the world and this is by ...",1
3,1212,"We booked an American Girl Place package at Fairmont Chicago Millennium Park. Told that we'd have a room with a nice view, apparently their idea of a nice view is of another building! Ended up getting a smoking room when we booked non-smoking, cost us $100 more a night than we were told, and staff was incredibly rude at the restaurant. Would never recommend coming here for any reason whatsoever!\n",0
4,637,"The Ambassador East Hotel is a business that certainly strives to keep its customers satisfied. Upon my entrance at the Ambassador East, I was greeted warmly. The staff was incredibly pleasant, and the accommodations were top-knotch. The food served at the award-winning 'Pump Room' was to die for, and the service was fast but friendly. \n",0

In [12]:
# Cleaning Raw tweets
def clean_text(text):
    
    #remove emails
    text = ' '.join([i for i in text.split() if '@' not in i])
    
    #remove web address
    text = re.sub('http[s]?://\S+', '', text)

    #remove brackets and parantheses (and removing the text inside the brackets and parantheses)
    text = re.sub("[\(\[].*?[\)\]]", "", text)

    #remove punctuations
    text = re.sub(r'[^\w\s]', ' ', text)
    
    #Filter to allow only alphabets and numbers
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    
    #Remove Unicode characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    #remove double spaces 
    text = re.sub('\s+', ' ', text)
    
    return text

In [13]:
# applying that into function.
df["clean_text"] = df['text'].apply(lambda x: clean_text(x))
df.head(10)

,Index,text,Class,clean_text
0,701,"My wife and I recently stayed at this hotel for a fun anniversary weekend away from the kids. Upon check in we were pleasantly surprised by the decor, the location to so many downtown attractions and the attentiveness of the staff. As a seasoned traveler for business I consider myself somewhat savvy when it comes to service and accommodations. This hotel certainly delivers on both accounts. My wife and I had not intended on eating in the hotel restaurant, but after reviewing the menu we thought we would give it a try. WOW! Service was outstanding and the food was amazing. We truly enjoyed our dining experience. All in all I would not hesitate to recommend this hotel to anyone I meet. \n",0,My wife and I recently stayed at this hotel for a fun anniversary weekend away from the kids Upon check in we were pleasantly surprised by the decor the location to so many downtown attractions and the attentiveness of the staff As a seasoned traveler for business I consider myself somewhat savvy when it comes to service and accommodations This hotel certainly delivers on both accounts My wife and I had not intended on eating in the hotel restaurant but after reviewing the menu we thought we would give it a try WOW Service was outstanding and the food was amazing We truly enjoyed our dining experience All in all I would not hesitate to recommend this hotel to anyone I meet
1,1171,"When you check into a hotel after being stuck in a airport, you areusually not in the best of mood. I, working in a upscale hotel, do encounter many guests checking in who this has happened to. All they want is a friendly face and a smooth check in. The desk clerk who checked me in at this property, did neither. She was short, rude, handed me my keys and walked away. I would never go back to this property due to this.\n",1,When you check into a hotel after being stuck in a airport you areusually not in the best of mood I working in a upscale hotel do encounter many guests checking in who this has happened to All they want is a friendly face and a smooth check in The desk clerk who checked me in at this property did neither She was short rude handed me my keys and walked away I would never go back to this property due to this
2,869,"Maybe it was because we booked thru priceline that we were treated like second rate guest - couldn't get a room thru Fairmont website as busy weekend with Ryder Cup.....but never have had this experience in using priceline before. The night time check in girl was rude and unhelpful. We were told no options to pay for upgrade or king bed and that we were stuck with two tiny beds and a ugly room. We had comforter with dirt in several places - and a bathroom for handicap with no counter space - had to use ironing board for toiletries. This hotel is huge and not at capacity - may have had a renovation but the good look of this hotel stops at the lobby. Hallways, rooms, carpet run down - just not what you come to expect of a fairmont. I have stayed in many all over the world and this is by ...",1,Maybe it was because we booked thru priceline that we were treated like second rate guest couldn t get a room thru Fairmont website as busy weekend with Ryder Cup but never have had this experience in using priceline before The night time check in girl was rude and unhelpful We were told no options to pay for upgrade or king bed and that we were stuck with two tiny beds and a ugly room We had comforter with dirt in several places and a bathroom for handicap with no counter space had to use ironing board for toiletries This hotel is huge and not at capacity may have had a renovation but the good look of this hotel stops at the lobby Hallways rooms carpet run down just not what you come to expect of a fairmont I have stayed in many all over the world and this is by far the worst Maybe be...
3,1212,"We booked an American Girl Place package at Fairmont Chicago Millennium Park. Told that we'd have a room with a nice view, apparently their idea of a nice view is of another building! Ended up getting a smoking room when we booked non-smoking, cost us $100 more a night than we were told, and staff was incredibly rude at the restaurant. Would never recommend coming here for any reason whatsoever!\n",0,We booked an American Girl Place package at Fairmont Chicago Millennium Park Told that we d have a room with a nice view apparently their idea of a nice view is of another building Ended up getting a smoking room when we booked non smoking cost us more a night than we were told and staff was incredibly rude at the restaurant Would never recommend coming here for any reason whatsoever
4,637,"The Ambassador East Hotel is a business that certainly strives to keep its customers satisfied. Upon my entrance at the Ambassador East, I was greeted warmly. The staff was incredibly pleasant, and the accommodations were top-knotch. The food served at the award-winning 'Pump Room' was to die for, and the service was fast but friendly. \n",0,The Ambassador East Hotel is a business that certainly strives to keep its customers satisfied Upon my entrance at the Ambassador East I was greeted warmly The staff was incredibly pleasant and the accommodations were top knotch The food served at the award winning Pump Room was to die for and the service was fast but friendly
5,1454,"I really wish I could say that I liked this hotel, but the whole experience was just plain awful. My first warning sign should have been when I made my reservation. The person I spoke with when placing my reservation had absolutely no idea what he was doing. At first he tried to book me into the wrong hotel, and then when we finally got it sorted which hotel I was actually wanting, he booked me for the wrong dates. He read me the right dates, and it was only when I called back two days later to confirm that I found out he'd given me the wrong dates. Hilton did get it fixed, but I already had a bad feeling about my stay. Then came actually staying at the hotel. The people at the check-in desk were downright rude. Then there was the room. I was supposed to be in a non-smoking room, but t...",0,I really wish I could say that I liked this hotel but the whole experience was just plain awful My first warning sign should have been when I made my reservation The person I spoke with when placing my reservation had absolutely no idea what he was doing At first he tried to book me into the wrong hotel and then when we finally got it sorted which hotel I was actually wanting he booked me for the wrong dates He read me the right dates and it was only when I called back two days later to confirm that I found out he d given me the wrong dates Hilton did get it fixed but I already had a bad feeling about my stay Then came actually staying at the hotel The people at the check in desk were downright rude Then there was the room I was supposed to be in a non smoking room but the room smelled...
6,212,"Very quaint and romantic, yet masculine. I've noticed that at most Chicago hotel bars it's hard to get a drink much less a seat but I guess because it's a small hotel that was not a problem at the Talbott - plus people take their drinks out to the seating in the lobby because it's so inviting - cozy and comfortable - love that! Would love to stay again but I must say that I was surprised by all the comments on the comfortable beds - ours was too firm. Also note there is no gym on the premises - but walking and shopping is enough of a workout! \n",1,Very quaint and romantic yet masculine I ve noticed that at most Chicago hotel bars it s hard to get a drink much less a seat but I guess because it s a small hotel that was not a problem at the Talbott plus people take their drinks out to the seating in the lobby because it s so inviting cozy and comfortable love that Would love to stay again but I must say that I was surprised by all the comments on the comfortable beds ours was too firm Also note there is no gym on the premises but walking and shopping is enough of a workout
7,478,"The Omni Chicago Hotel is amazing little get away right on the Magnificent Mile in Chicago. This hotel is warm and homey as well as modern and filled with amenities! The beds are very comfortable and there are flat screen televisions in the rooms (at least both times I have stayed). The Windy City Spa provides a relaxing getaway as well.The indoor pool provides something fun for all ages and the customer service was excellent. The garage was very secure and has unlimited in/out priviledges which made it nice to be able to access the car as much as you wanted without any penalty. All in all, well worth it and will plan to stay again!\n",0,The Omni Chicago Hotel is amazing little get away right on the Magnificent Mile in Chicago This hotel is warm and homey as well as modern and filled with amenities The beds are very comfortable and there are flat screen televisions in the rooms The Windy City Spa provides a relaxing getaway as well The indoor pool provides something fun for all ages and the customer service was excellent The garage was very secure and has unlimited in out priviledges which made it nice to be able to access the car as much as you wanted without any penalty All in all well worth it and will plan to stay again
8,456,"I have just returned from my first stay at the remodeled Fairmont Chicago Millennium Park and all I can say is fabulous! The modern decor and style hits you the minute you walk in. The front desk is a work of art. I stayed in the anything but standard guestroom. The modern decor, the beautiful artwork, this is the most relaxing hotel room I have ever stayed in. The bathroom is like having your own personal spa, all the marble tile is classic and modern at the same time. The rainfall showerhead is to die for people. If you have the time be sure to check out the fitness center and spa. Great new equipment to work up a sweat and all the pampering a body could ever needs awaits in the spa. I wish I could have stayed longer, next time I will be sure to add a couple of 'me' days to my trip a...",0,I have just returned from my first stay at the remodeled Fairmont Chicago Millennium Park and all I can say is fabulous The modern decor and style hits you the minute you walk in The front desk is a work of art I stayed in the anything but standard guestroom The modern decor the beautiful artwork this is the most relaxing hotel room I have ever stayed in The bathroom is like having your own personal spa all the marble tile is classic and modern at the same time The rainfall showerhead is to die for people If you have the time be sure to check out the fitness center and spa Great new equipment to work up a sweat and all the pampering a body could ever needs awaits in the spa I wish I could have stayed longer next time I will be sure to add a couple of me days to my trip and I m sure I w...
9,77,"My husband and I had a wonderful stay at the Omni Chicago Hotel. I had contacted the customer service representative prior to our stay to request a quiet suite. When we arrived, she greeted us and confirmed that we were getting exactly what I had requested--and more. Our suite had a partial view of the lake!!! And, we were able to check in early. The service at this hotel is incredible. Everyone made us feel welcome and took care to respond to any question or request that we had. The suite was very quiet even though we were on the east side of the hotel, very near to Michigan Avenue. Housekeeping was prompt and thorough. We really couldn't have asked for a better hotel. We will definitely stay there on future trips to Chicago and will recommend this hotel to anyone who travels there. \n",1,My husband and I had a wonderful stay at the Omni Chicago Hotel I had contacted the customer service representative prior to our stay to request a quiet suite When we arrived she greeted us and confirmed that we were getting exactly what I had requested and more Our suite had a partial view of the lake And we were able to check in early The service at this hotel is incredible Everyone made us feel welcome and took care to respond to any question or request that we had The suite was very quiet even though we were on the east side of the hotel very near to Michigan Avenue Housekeeping was prompt and thorough We really couldn t have asked for a better hotel We will definitely stay there on future trips to Chicago and will recommend this hotel to anyone who travels there

In [14]:
# dropping the uncleaned text column "text"
df = df.drop(['text'], axis=1)

In [15]:
# renaming the column
df.rename(columns = {'clean_text':'text'}, inplace = True)
df.head()

,Index,Class,text
0,701,0,My wife and I recently stayed at this hotel for a fun anniversary weekend away from the kids Upon check in we were pleasantly surprised by the decor the location to so many downtown attractions and the attentiveness of the staff As a seasoned traveler for business I consider myself somewhat savvy when it comes to service and accommodations This hotel certainly delivers on both accounts My wife and I had not intended on eating in the hotel restaurant but after reviewing the menu we thought we would give it a try WOW Service was outstanding and the food was amazing We truly enjoyed our dining experience All in all I would not hesitate to recommend this hotel to anyone I meet
1,1171,1,When you check into a hotel after being stuck in a airport you areusually not in the best of mood I working in a upscale hotel do encounter many guests checking in who this has happened to All they want is a friendly face and a smooth check in The desk clerk who checked me in at this property did neither She was short rude handed me my keys and walked away I would never go back to this property due to this
2,869,1,Maybe it was because we booked thru priceline that we were treated like second rate guest couldn t get a room thru Fairmont website as busy weekend with Ryder Cup but never have had this experience in using priceline before The night time check in girl was rude and unhelpful We were told no options to pay for upgrade or king bed and that we were stuck with two tiny beds and a ugly room We had comforter with dirt in several places and a bathroom for handicap with no counter space had to use ironing board for toiletries This hotel is huge and not at capacity may have had a renovation but the good look of this hotel stops at the lobby Hallways rooms carpet run down just not what you come to expect of a fairmont I have stayed in many all over the world and this is by far the worst Maybe be...
3,1212,0,We booked an American Girl Place package at Fairmont Chicago Millennium Park Told that we d have a room with a nice view apparently their idea of a nice view is of another building Ended up getting a smoking room when we booked non smoking cost us more a night than we were told and staff was incredibly rude at the restaurant Would never recommend coming here for any reason whatsoever
4,637,0,The Ambassador East Hotel is a business that certainly strives to keep its customers satisfied Upon my entrance at the Ambassador East I was greeted warmly The staff was incredibly pleasant and the accommodations were top knotch The food served at the award winning Pump Room was to die for and the service was fast but friendly

In [16]:
import spacy
#loading the english language small model of spacy
en = spacy.load('en_core_web_sm')
sw_spacy = en.Defaults.stop_words
print(sw_spacy)

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

{'is', 'same', 'several', 'themselves', 'nobody', 'whereupon', 'amount', 'this', 'about', 'front', 'be', 'meanwhile', 'ourselves', 'ca', 'every', 'whence', 'my', 'alone', 'wherever', 'already', 'whether', 'done', 'none', 'them', 'should', 'somewhere', '‘ve', 'down', 'might', 'always', 'say', 'him', 'by', 'that', 'became', 'still', 'take', '‘d', 'used', 'wherein', 'empty', 'us', 'bottom', 'thereupon', 'onto', 'me', 'whatever', 'whereafter', 'give', 'twenty', 'n‘t', 'your', 'anyone', 'anyhow', 'whole', 'amongst', 'therein', 'really', 'did', 'now', 'everything', 'except', 'never', 'at', 'hereafter', 'beside', '’d', 'where', 'upon', 'across', 'their', 'first', 'four', 'hereupon', 'could', 'will', 'also', 'but', 'behind', 'after', '‘m', 'it', 'one', 'very', 'without', 'must', 'both', 'most', 'below', 'would', 'her', 'into', 'all', 'please', 'when', 'each', 'beyond', 'sometimes', 'an', 'these', 'see', 'sixty', 'top', 'nor', 'per', 'almost', 'until', 'between', 'among', 'just', 'they', "'ve", 'again', 'hence', 'other', 'yet', 'out', 'whose', 'many', 'i', 'via', 'others', 'eleven', 'thereafter', 'whoever', 'six', 'off', "'ll", 'thus', 'something', 'whereas', 'you', 'from', 'which', 'another', 'than', 'however', 'though', 'quite', 'he', 'two', 'go', 'namely', 'some', 'a', 'she', 'doing', 'during', 'somehow', 'latterly', 'yourselves', 'ten', 're', 'herself', 'mostly', 'n’t', 'so', 'because', 'third', '’s', 'of', 'anything', 'along', 'own', 'three', 'various', 'any', 'ever', 'fifteen', 'becoming', 'if', 'fifty', 'or', 'keep', 'only', 'with', 'as', 'towards', 'few', 'moreover', 'hundred', 'back', 'on', 'once', 'those', 'least', 'seems', 'elsewhere', 'since', 'above', 'while', 'had', 'even', 'myself', "'re", 'the', 'thence', 'our', 'move', "'s", 'becomes', '‘s', 'regarding', 'although', 'itself', 'everyone', 'for', 'am', 'have', 'further', 'former', 'nothing', 'forty', 'been', 'not', 'over', 'anywhere', 'what', 'everywhere', 'against', 'its', 'nine', 'enough', 'sometime', 'someone', 'no', 'noone', "'d", 'toward', 'throughout', 'less', 'together', '’m', '‘re', 'around', 'call', '’ll', 'may', 'there', 'make', 'cannot', 'well', 'made', 'thru', 'can', 'five', 'being', 'whereby', '’ve', 'therefore', 'seeming', 'through', 'under', 'mine', 'put', 'side', 'himself', 'has', "'m", 'yours', 'then', 'ours', 'otherwise', 'do', 'full', 'here', 'hers', 'we', 'nowhere', 'else', 'neither', 'latter', 'was', 'too', 'herein', 'and', 'eight', 'anyway', '‘ll', 'how', 'up', 'serious', 'get', 'why', 'yourself', '’re', 'unless', 'thereby', 'his', 'more', 'whither', 'are', 'afterwards', 'become', 'perhaps', 'before', 'such', 'either', 'due', 'next', 'does', 'whenever', 'who', 'name', 'in', 'formerly', 'last', 'were', 'show', 'beforehand', 'part', "n't", 'often', 'hereby', 'within', 'seemed', 'to', 'indeed', 'using', 'rather', 'much', 'nevertheless', 'twelve', 'whom', 'seem', 'besides'}

In [17]:
import nltk
from nltk.corpus import stopwords
sw_nltk = stopwords.words('english')
print(sw_nltk)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [18]:
sw_nltk.extend(['th','stay'])
print(len(sw_nltk))

181

In [19]:
# preprocessing the data (removing stopwords, convert the sentence to lower case, and also applying lemmatization to get meaningful words )
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
#stop_words = set(stopwords.words('english'))
ps=PorterStemmer()
wnl=WordNetLemmatizer()
def clean_lemma(review):
    review = review.lower()
    review = review.split()
    review = [wnl.lemmatize(word) for word in review if word not in sw_nltk]
    review = [wnl.lemmatize(word) for word in review if word not in sw_spacy]
    review = ' '.join(review)
    return review

In [20]:
# using lemmatization
df['text']=df['text'].apply(clean_lemma)
df.head()

,Index,Class,text
0,701,0,wife recently stayed hotel fun anniversary weekend away kid check pleasantly surprised decor location downtown attraction attentiveness staff seasoned traveler business consider somewhat savvy come service accommodation hotel certainly delivers account wife intended eating hotel restaurant reviewing menu thought try wow service outstanding food amazing truly enjoyed dining experience hesitate recommend hotel meet
1,1171,1,check hotel stuck airport areusually best mood working upscale hotel encounter guest checking happened want friendly face smooth check desk clerk checked property short rude handed key walked away property
2,869,1,maybe booked priceline treated like second rate guest room fairmont website busy weekend ryder cup experience priceline night time check girl rude unhelpful told option pay upgrade king bed stuck tiny bed ugly room comforter dirt place bathroom handicap counter space use ironing board toiletry hotel huge capacity renovation good look hotel stop lobby hallway room carpet run come expect fairmont stayed world far worst maybe low floor updated paid guest fairmont gold member positive great location daytime staff helpful desk bike borrow handy view great higher room checked raddison blu street looked nicer
3,1212,0,booked american girl place package fairmont chicago millennium park told room nice view apparently idea nice view building ended getting smoking room booked non smoking cost u night told staff incredibly rude restaurant recommend coming reason whatsoever
4,637,0,ambassador east hotel business certainly strives customer satisfied entrance ambassador east greeted warmly staff incredibly pleasant accommodation knotch food served award winning pump room die service fast friendly

In [21]:
df1 = df.sort_values(by=['Index'], ascending=True)
df1.head()

,Index,Class,text
1110,1,1,stayed night getaway family thursday triple aaa rate steal floor room complete plasma tv bose stereo voss evian water gorgeous bathroom concierge helpful beat location flaw breakfast pricey service slow table restaurant food good worth wait return heartbeat gem chicago
493,2,1,triple rate upgrade view room le included breakfast voucher great view river lake wrigley bldg tribune bldg major restaurant shopping sightseeing attraction walking distance large room comfortable bed
388,3,1,come little late finally catching review past month dear friend stayed hyatt regency late october night visiting friend husband town hotel perfect imo easy check check lovely clean comfortable room great view city know area pretty convenient downtown chicago attraction dinner went clubing friend division st problem getting cab forth hyatt public transportation right near bother needed cab hotel parking usual chicago expensive able car quickly problem best got rate hotwire downright steal area chicago quality hotel
1078,4,1,omni chicago delivers spaciousness room helpful staff prized location michigan avenue address chicago requires high level quality omni delivers check group people minute staff plentiful recommendation dining event room largest find price range chicago standard room separate living area work desk fitness center free weight weight machine row cardio equipment shared room feel cramped way great property
1184,5,1,asked high floor away elevator got room pleasantly decorated functional clean need lot service pleasant prompt fitness center equipped working order great location end michigan avenue shopping district

In [22]:
df1.reset_index(drop=True, inplace=True)

In [23]:
df1.head()

,Index,Class,text
0,1,1,stayed night getaway family thursday triple aaa rate steal floor room complete plasma tv bose stereo voss evian water gorgeous bathroom concierge helpful beat location flaw breakfast pricey service slow table restaurant food good worth wait return heartbeat gem chicago
1,2,1,triple rate upgrade view room le included breakfast voucher great view river lake wrigley bldg tribune bldg major restaurant shopping sightseeing attraction walking distance large room comfortable bed
2,3,1,come little late finally catching review past month dear friend stayed hyatt regency late october night visiting friend husband town hotel perfect imo easy check check lovely clean comfortable room great view city know area pretty convenient downtown chicago attraction dinner went clubing friend division st problem getting cab forth hyatt public transportation right near bother needed cab hotel parking usual chicago expensive able car quickly problem best got rate hotwire downright steal area chicago quality hotel
3,4,1,omni chicago delivers spaciousness room helpful staff prized location michigan avenue address chicago requires high level quality omni delivers check group people minute staff plentiful recommendation dining event room largest find price range chicago standard room separate living area work desk fitness center free weight weight machine row cardio equipment shared room feel cramped way great property
4,5,1,asked high floor away elevator got room pleasantly decorated functional clean need lot service pleasant prompt fitness center equipped working order great location end michigan avenue shopping district

### FEATURE EXTRACTION (using TFIDF)

In [24]:
x = df1['text']
y = df1['Class']

In [25]:
y

0       1
1       1
2       1
3       1
4       1
       ..
1595    0
1596    0
1597    0
1598    0
1599    0
Name: Class, Length: 1600, dtype: int64

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
corpii=cv.fit_transform(x)

In [27]:
feature_names = cv.get_feature_names()
#feature_names

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [28]:
len(feature_names)

7905

In [29]:
u1 = pd.DataFrame(corpii.toarray(), columns=feature_names)
u1.head()

,aaa,aaahed,aback,abassador,abd,ability,able,abound,abrupt,abruptly,...,yucky,yummo,yummy,yunan,yup,zagat,zest,zipped,zone,zoo
0,0.217034,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.090437,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### FEATURE SELECTION (using chi square)

In [30]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# Two features with highest chi-squared statistics are selected
chi2_features = SelectKBest(chi2, k = 2000)
X_kbest_features = chi2_features.fit_transform(u1, y)

In [31]:
chi_support = chi2_features.get_support()

In [32]:
chi_feature = u1.loc[:,chi_support].columns.tolist()

In [33]:
X_kbest_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
u3 = pd.DataFrame(X_kbest_features, columns = chi_feature)
u3.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yellow,yep,yes,yo,yoga,young,youve,yr,yummy,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
X1 = pd.concat([u3, y], axis=1)
X1.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yep,yes,yo,yoga,young,youve,yr,yummy,zone,Class
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [36]:
u3.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yellow,yep,yes,yo,yoga,young,youve,yr,yummy,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
df1['Class'].value_counts()

1    800
0    800
Name: Class, dtype: int64

In [38]:
#node_Class
node_Class = df1["Class"]

### Distance calculation for creating adjacency matrix

In [39]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'hamming')
s

array([[0.    , 0.019 , 0.0275, ..., 0.0195, 0.0195, 0.0295],
       [0.019 , 0.    , 0.0255, ..., 0.0185, 0.0175, 0.0285],
       [0.0275, 0.0255, 0.    , ..., 0.025 , 0.0255, 0.034 ],
       ...,
       [0.0195, 0.0185, 0.025 , ..., 0.    , 0.0175, 0.0275],
       [0.0195, 0.0175, 0.0255, ..., 0.0175, 0.    , 0.028 ],
       [0.0295, 0.0285, 0.034 , ..., 0.0275, 0.028 , 0.    ]])

In [40]:
X1=pd.DataFrame(s)
X1

,0,1,2,3,4,5,6,7,8,9,...,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599
0,0.0000,0.0190,0.0275,0.0215,0.0160,0.0235,0.0235,0.0220,0.0215,0.0230,...,0.0165,0.0280,0.0210,0.0160,0.0205,0.0210,0.0220,0.0195,0.0195,0.0295
1,0.0190,0.0000,0.0255,0.0200,0.0140,0.0230,0.0235,0.0205,0.0190,0.0185,...,0.0145,0.0265,0.0195,0.0145,0.0190,0.0185,0.0195,0.0185,0.0175,0.0285
2,0.0275,0.0255,0.0000,0.0280,0.0235,0.0300,0.0325,0.0290,0.0275,0.0270,...,0.0220,0.0355,0.0275,0.0230,0.0275,0.0260,0.0275,0.0250,0.0255,0.0340
3,0.0215,0.0200,0.0280,0.0000,0.0145,0.0250,0.0255,0.0225,0.0220,0.0225,...,0.0170,0.0295,0.0220,0.0170,0.0210,0.0205,0.0215,0.0200,0.0200,0.0305
4,0.0160,0.0140,0.0235,0.0145,0.0000,0.0195,0.0200,0.0175,0.0165,0.0175,...,0.0120,0.0240,0.0160,0.0115,0.0165,0.0155,0.0165,0.0150,0.0145,0.0255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.0210,0.0185,0.0260,0.0205,0.0155,0.0230,0.0240,0.0210,0.0195,0.0210,...,0.0145,0.0270,0.0195,0.0155,0.0190,0.0000,0.0195,0.0180,0.0180,0.0280
1596,0.0220,0.0195,0.0275,0.0215,0.0165,0.0240,0.0255,0.0230,0.0205,0.0215,...,0.0150,0.0265,0.0200,0.0155,0.0200,0.0195,0.0000,0.0185,0.0180,0.0280
1597,0.0195,0.0185,0.0250,0.0200,0.0150,0.0220,0.0235,0.0205,0.0190,0.0200,...,0.0140,0.0260,0.0180,0.0150,0.0185,0.0180,0.0185,0.0000,0.0175,0.0275
1598,0.0195,0.0175,0.0255,0.0200,0.0145,0.0220,0.0235,0.0215,0.0190,0.0200,...,0.0140,0.0255,0.0180,0.0130,0.0185,0.0180,0.0180,0.0175,0.0000,0.0280
1599,0.0295,0.0285,0.0340,0.0305,0.0255,0.0320,0.0330,0.0315,0.0285,0.0315,...,0.0230,0.0345,0.0285,0.0240,0.0280,0.0280,0.0280,0.0275,0.0280,0.0000

In [41]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.023867485546875

In [42]:
adjmat_df=X1.copy()

In [43]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [44]:
# adjacency matrix
adjmat_df

,0,1,2,3,4,5,6,7,8,9,...,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1596,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1597,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1598,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1599,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0

In [45]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [46]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [47]:
from stellargraph import StellarGraph
graph1= StellarGraph.from_networkx(H)
print(graph1.info())

StellarGraph: Undirected multigraph
 Nodes: 1600, Edges: 573287

 Node types:
  default: [1600]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [573287]
        Weights: all 1 (default)
        Features: none

In [48]:
from stellargraph.data import BiasedRandomWalk
from stellargraph import StellarGraph
from stellargraph import datasets
from IPython.display import display, HTML

%matplotlib inline

In [49]:
rw = BiasedRandomWalk(graph1)

walks = rw.run(
    nodes=list(graph1.nodes()),  # root nodes
    length=100,  # maximum length of a random walk
    n=10,  # number of random walks per root node
    p=0.5,  # Defines (unormalised) probability, 1/p, of returning to source node
    q=2.0,  # Defines (unormalised) probability, 1/q, for moving away from source node
)
print("Number of random walks: {}".format(len(walks)))
from gensim.models import Word2Vec

str_walks = [[str(n) for n in walk] for walk in walks]
model = Word2Vec(str_walks, size=32, window=5, min_count=0, sg=1, workers=2, iter=5, seed = 10)

Number of random walks: 16000

In [50]:
# The embedding vectors can be retrieved from model.wv using the node ID as key.
model.wv["241"].shape

(32,)

In [51]:
# Retrieve node embeddings and corresponding subjects
node_ids = model.wv.index2word  # list of node IDs

node_embeddings = (
    model.wv.vectors
)  # numpy.ndarray of size number of nodes times embeddings dimensionality
node_targets = node_Class[[int(node_id) for node_id in node_ids]]

In [52]:
node_emb=pd.DataFrame(node_embeddings)

In [53]:
node_tar=pd.DataFrame(node_targets)
node_targets=node_tar.sort_index()

In [54]:
node_emb['Class']=node_targets

### Node embeddings

In [55]:
node_emb

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,Class
0,0.104378,0.241601,-0.331948,0.049302,0.038251,-0.328385,0.195420,-0.042423,-0.048630,-0.271697,...,0.107918,-0.013446,0.043607,-0.145954,-0.055236,-0.169753,0.174522,-0.106203,-0.034778,1
1,0.273722,0.091341,-0.417166,0.023155,-0.100619,-0.341593,0.399132,-0.131587,0.089544,-0.159036,...,0.053509,0.124100,0.170645,-0.129811,0.020307,-0.012678,0.438186,-0.016344,-0.091935,1
2,-0.093997,0.125444,-0.323929,0.041202,-0.125915,-0.463301,0.361798,-0.062634,-0.032898,-0.211549,...,0.022106,-0.023021,0.090296,-0.215690,-0.044409,0.034006,0.141267,-0.112612,0.066067,1
3,-0.037021,0.145114,-0.284607,-0.170562,0.154449,-0.377091,0.350423,0.088789,-0.004977,0.023643,...,0.069577,0.358062,0.133929,0.018974,-0.146856,-0.061889,0.169442,0.079933,-0.004982,1
4,0.296895,0.179658,-0.293168,0.023385,0.033732,-0.353397,0.331948,0.034406,0.038579,-0.139967,...,0.140958,0.002280,0.152175,-0.136917,0.034591,0.096253,0.123378,-0.023234,-0.189880,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,-0.046223,-0.347713,-0.492808,0.124223,0.180863,-0.402665,-0.122904,-0.004842,0.614262,-0.391203,...,0.278463,0.409003,0.628751,-0.027553,-0.079453,-0.164297,0.249307,-0.424430,0.083003,0
1596,0.039538,-0.350498,-0.333871,0.195554,0.274841,-0.578959,-0.103202,0.094749,0.624429,-0.486667,...,0.300441,0.605631,0.635626,-0.043531,-0.101081,-0.300250,0.147083,-0.264010,-0.019857,0
1597,-0.065471,-0.474487,-0.614049,0.135077,0.305365,-0.453250,-0.030542,-0.082301,0.587332,-0.330370,...,0.315575,0.307804,0.590560,-0.059648,-0.252645,-0.253414,0.221562,-0.242604,-0.067111,0
1598,0.132643,-0.312059,-0.427197,0.277235,0.212642,-0.498894,-0.063055,-0.062953,0.717198,-0.297159,...,0.244693,0.362486,0.589355,-0.134361,-0.110344,0.008231,0.267386,-0.287464,-0.042343,0
1599,-0.141284,-0.242995,-0.416904,0.181130,0.258431,-0.494036,-0.098958,-0.118807,0.698995,-0.465734,...,0.351133,0.448171,0.587983,0.013301,-0.127819,-0.104413,0.237567,-0.347626,0.060871,0

In [56]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns

In [57]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

## Model Building

### CROSS VALIDATION

In [58]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [59]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.954375
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       800
           1       0.95      0.96      0.95       800

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600

Confusion matrix:  [[760  40]
 [ 33 767]]

In [60]:
from sklearn.linear_model import PassiveAggressiveClassifier
pag=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    pag.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(pag.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.94375
              precision    recall  f1-score   support

           0       0.96      0.93      0.94       800
           1       0.93      0.96      0.94       800

    accuracy                           0.94      1600
   macro avg       0.94      0.94      0.94      1600
weighted avg       0.94      0.94      0.94      1600

Confusion matrix:  [[742  58]
 [ 32 768]]

In [61]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9525
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       800
           1       0.95      0.96      0.95       800

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600

Confusion matrix:  [[757  43]
 [ 33 767]]

In [62]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9625
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       800
           1       0.96      0.96      0.96       800

    accuracy                           0.96      1600
   macro avg       0.96      0.96      0.96      1600
weighted avg       0.96      0.96      0.96      1600

Confusion matrix:  [[770  30]
 [ 30 770]]

In [63]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.95125
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       800
           1       0.95      0.95      0.95       800

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600

Confusion matrix:  [[764  36]
 [ 42 758]]

In [64]:
abc = AdaBoostClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    abc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(abc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9325
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       800
           1       0.93      0.94      0.93       800

    accuracy                           0.93      1600
   macro avg       0.93      0.93      0.93      1600
weighted avg       0.93      0.93      0.93      1600

Confusion matrix:  [[744  56]
 [ 52 748]]

In [65]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.951875
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       800
           1       0.95      0.95      0.95       800

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600

Confusion matrix:  [[763  37]
 [ 40 760]]

### Train - test split (Without cross validation)

In [66]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [67]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[154   6]
 [ 20 140]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       160
           1       0.96      0.88      0.92       160

    accuracy                           0.92       320
   macro avg       0.92      0.92      0.92       320
weighted avg       0.92      0.92      0.92       320

accuracy_score:  0.91875

In [68]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[150  10]
 [  9 151]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       160
           1       0.94      0.94      0.94       160

    accuracy                           0.94       320
   macro avg       0.94      0.94      0.94       320
weighted avg       0.94      0.94      0.94       320

accuracy_score:  0.940625

In [69]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[153   7]
 [  7 153]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       160
           1       0.96      0.96      0.96       160

    accuracy                           0.96       320
   macro avg       0.96      0.96      0.96       320
weighted avg       0.96      0.96      0.96       320

accuracy_score:  0.95625

In [70]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[151   9]
 [  8 152]]
              precision    recall  f1-score   support

           0       0.95      0.94      0.95       160
           1       0.94      0.95      0.95       160

    accuracy                           0.95       320
   macro avg       0.95      0.95      0.95       320
weighted avg       0.95      0.95      0.95       320

accuracy_score:  0.946875

In [71]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[150  10]
 [  7 153]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       160
           1       0.94      0.96      0.95       160

    accuracy                           0.95       320
   macro avg       0.95      0.95      0.95       320
weighted avg       0.95      0.95      0.95       320

accuracy_score:  0.946875

In [72]:
gbc = GradientBoostingClassifier(n_estimators=300)
gbc.fit(x_train, y_train)
y_pred=gbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[152   8]
 [  6 154]]
              precision    recall  f1-score   support

           0       0.96      0.95      0.96       160
           1       0.95      0.96      0.96       160

    accuracy                           0.96       320
   macro avg       0.96      0.96      0.96       320
weighted avg       0.96      0.96      0.96       320

accuracy_score:  0.95625

In [73]:
abc = AdaBoostClassifier(n_estimators=300)
abc.fit(x_train, y_train)
y_pred=abc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[149  11]
 [  8 152]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       160
           1       0.93      0.95      0.94       160

    accuracy                           0.94       320
   macro avg       0.94      0.94      0.94       320
weighted avg       0.94      0.94      0.94       320

accuracy_score:  0.940625

In [74]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
lgb.fit(x_train, y_train)
y_pred=lgb.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[152   8]
 [  8 152]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       160
           1       0.95      0.95      0.95       160

    accuracy                           0.95       320
   macro avg       0.95      0.95      0.95       320
weighted avg       0.95      0.95      0.95       320

accuracy_score:  0.95